Dev
creativeplatform/crtv3 pull request #80
Opened 2024-11-30 20:43 UTC by liberalterian

### Pull Request Summary: **Subtitles**  

This PR merges `liberalterian/dev` into `creativeplatform/crtv3` and includes several updates enabling subtitle functionality, token gating, and authentication workflows.  

#### Changes Include:  

1. **Components and Features**  
   - Added **SubtitlesContext**, **SubtitlesControl**, and **SubtitlesDisplay** components to manage and display subtitles effectively.  
   - Integrated the above components into the **Player** component for seamless subtitle support.  

2. **Multi-Language Support**  
   - Updated the **FileUpload** component with translations to enable support for multi-language subtitles.  

3. **Livepeer Audio-to-Text AI Pipeline**  
   - Implemented the **audioToText** server action to handle audio transcription for subtitle generation.  

4. **Token Gating**  
   - Fixed logic in **hasAccess/hasNft** within `tokenGate.ts`.  
   - Added token gating functionality to the **HookMultiStepForm** component.  
   - Added **webhook** in `/api/livepeer/token-gate/route.ts` to enable token gating for videos (incomplete and not yet in use)
   - Added `accessKey.ts` in /lib/ to generate and validate access keys in the token gate webhook

5. **Authentication**  
   - Added `authentication.ts` to `/api/auth/thirdweb/` for improved auth management.  

6. **Bug Fixes and Refinements**  
   - Fixed the **connectButtonWrapper** component by updating `getLoginPayload()` method and adding `wallet.disconnect()` in the `onDisconnect` prop

2024-12-02 14:53 UTC, amochuko reviewed
Nice one. The requested changes doesn't alter the codebase but just some house cleanup.

2024-12-02 14:53 UTC, amochuko commented on app/components/Videos/Upload/FileUpload.tsx
> +    // }
The commented-out lines can be removed.

2024-12-02 14:53 UTC, amochuko commented on app/components/Videos/Upload/index.tsx
> +        // });
The commented-out lines can be removed.

2024-12-02 14:53 UTC, amochuko commented on app/lib/sdk/orbisDB/context.tsx
> +    assetMetadataModelId: 'kjzl6hvfrbw6c6itfx7h76zcrpch2gm2u4bws8gxi0zvw1n8pg5v8rvli7b1blr',
I might be better if have such `magic string` defined as `CONSTANT` in a config file so it easy for update later in the future.

2024-12-02 21:37 UTC, liberalterian commented
@amochuko, I made the requested changes and they should be reflected in my most recent commit.

@sirgawain0x, I resolved the merge conflicts and you should be able to see that reflected in the recent commits I pushed ~1hr ago.

2024-12-03 05:57 UTC, sirgawain0x commented on app/api/livepeer/token-gate/route.ts
> +  const activeAccount = useActiveAccount();
Good eye! How would he get the active account on the server side?

2024-12-03 23:38 UTC, sirgawain0x commented
@liberalterian please review and test the above code recommedations.

2024-12-04 02:24 UTC, sirgawain0x requested changes
There are some code recommendations, some are potential issues ⚠️ or minor refactoring 🛠️ to consider.  Also there are some suggestions made by @amochuko and a discussion in https://github.com/creativeplatform/crtv3/pull/80/files#r1865869875 Where it needs to not use the client version of getting the user address.

2024-12-04 04:24 UTC, liberalterian commented on app/lib/sdk/orbisDB/models/AssetMetadata.ts
> +const createModel = async (modelDefinition: any, db: OrbisDB) => await db.ceramic.createModel(modelDefinition);
Instead of defining a custom ModelDefinition, I imported it from @ceramicnetwork/stream-model.

2024-12-04 04:27 UTC, liberalterian commented on app/components/Videos/Upload/index.tsx
> +            [subtitlesUri, setSubtitlesUri] = useState<string>();
Instead of defining a custom LivepeerAsset type I imported the Asset type from 'livepeer/models/components'.

2024-12-04 04:37 UTC, liberalterian commented on app/components/Videos/Upload/index.tsx
> +      ) {
Added requested update with alternative toast.error() message: "Access denied. Please ensure you are connected and have an active Creator Pass in your wallet."

2024-12-04 05:00 UTC, liberalterian commented on app/api/livepeer/token-gate/route.ts
> +  const activeAccount = useActiveAccount();
Yeah, this is just a starting point. There are multiple missing pieces including the question of how to get the users address to the webhook. 

This endpoint will need to be registered in the Livepeer Studio dashboard and will be called when the accessKey prop is provided to the Player component to handle access control for videos with playback policies enabling token gating. There could, in theory, be multiple webhooks since the playback policy requires the webhookId field, which points to the registered webhook in the Studio dashboard.

I am not 100% sure what the best solution is and I admit this does not follow the tutorial you included in the issue for token gating videos. _The question is whether or not I am doing this the right way at all._ 

I was wondering if we could encode data in the access key and decrypt it in the webhook? Some of the required data (i.e., token contract address and ID) will be included in the request body automatically passed to the webhook and is defined when calling the either the SDK's create or createViaUrl methdod as part of the playback policy. That being said, other fields, like the user's address, are not included in the webhook event.

I was just experimenting when I put this together but haven't yet been able to test anything. I'm not 100% sure if I am thinking about this the right way. I probably should've put these in a separate branch for now and submitted as part of a second PR once I had already answered these questions. 

Should we continue this conversation before making any decisions? I feel like we should probably reach out to Livepeer on Discord about this issue, as we still have a channel set up for this project on their server.

References:
- https://docs.livepeer.org/api-reference/asset/get
- https://docs.livepeer.org/developers/guides/access-control-webhooks

2024-12-04 05:00 UTC, liberalterian commented on app/lib/utils/scripts/createOrbisDbModels.ts
> +    string;
This is erroneous, the issue has already been resolved.

2024-12-04 05:01 UTC, liberalterian commented on app/lib/sdk/orbisDB/context.tsx
> +    isConnected: (address: string) => Promise<Boolean>;
Done!

2024-12-04 05:01 UTC, liberalterian commented on app/lib/sdk/orbisDB/context.tsx
> +    getAssetMetadata: (assetId: string) => Promise<AssetMetadata | null>;
This is erroneous as these methods are meant to accept _any_ value or updates.

2024-12-04 05:01 UTC, liberalterian commented on app/api/livepeer/translation/route.ts
> +    });
Done!

2024-12-04 05:01 UTC, liberalterian commented on app/api/livepeer/translation/route.ts
> +    formData.append('max_tokens', '256');
Done!

2024-12-04 05:02 UTC, liberalterian commented on package.json
> +    "@lit-protocol/sdk-nodejs": "^1.1.250",
This is a temporary measure and will be replaced with the use of the new /api/livepeer/translation/route.ts endpoint

2024-12-04 05:02 UTC, liberalterian commented on app/components/Videos/Upload/index.tsx
> +            };
Done!

2024-12-04 05:02 UTC, liberalterian commented on app/components/Videos/Upload/index.tsx
> +      ) {
Done!

2024-12-04 05:15 UTC, liberalterian commented on app/api/auth/[...nextAuth].ts
> +      domain: "http://localhost:3000",
I apologize, this was something I was going to experiment with to replace the token gating effect in /components/Videos/Upload/index.tsx but I never finished experimenting with it and it should not have been included in this PR. I removed it and will push a commit with that update in a few minutes.

2024-12-04 05:15 UTC, liberalterian commented on app/api/auth/thirdweb/gateCondition.ts
> +  // console.log({ creatorPassAnnualBalance, creatorPass3MonthBalance });
Done!

2024-12-04 05:16 UTC, liberalterian commented on app/api/auth/thirdweb/gateCondition.ts
> +  // console.log({ hasPass });
Done!

2024-12-04 05:16 UTC, liberalterian commented on app/api/livepeer/actions.ts
>      console.log('Created: ', asset);
Done!

2024-12-04 05:16 UTC, liberalterian commented on app/api/livepeer/actions.ts
>      console.log('Created: ', asset);
Done!

2024-12-04 05:18 UTC, liberalterian commented on app/components/Videos/Upload/FileUpload.tsx
> +    // }
Done!

2024-12-04 05:19 UTC, liberalterian commented on app/lib/sdk/orbisDB/context.tsx
> +    assetMetadataModelId: 'kjzl6hvfrbw6c6itfx7h76zcrpch2gm2u4bws8gxi0zvw1n8pg5v8rvli7b1blr',
Done! I added this to the /lib/utils/context.tsx.

2024-12-04 05:25 UTC, liberalterian commented on app/api/livepeer/translation/route.ts
> +    console.log('Translation request:', body);
Done!

2024-12-04 05:27 UTC, liberalterian commented on app/api/livepeer/translation/route.ts
> +}
Done!

2024-12-04 05:28 UTC, liberalterian commented on app/api/livepeer/translation/route.ts
> +    formData.append('max_tokens', '256');
This is erroneous, default values for model_id and max_tokens fields in POST /llm request should not be defined as environment variables.

2024-12-04 05:33 UTC, liberalterian commented on app/api/livepeer/translation/route.ts
> +    }
This is erroneous as this endpoint is meant to support any arbitrary language. Currently, the FileUpload component translates subtitles to Chinese, German, and Spanish by default but later versions _could_ allow users to provide additional languages for subtitle translation. 

I did however add the type checking you recommend to ensure text, source, and target are all strings.

2024-12-04 05:35 UTC, liberalterian commented on app/lib/sdk/orbisDB/context.tsx
> +
Done!

2024-12-04 05:37 UTC, liberalterian commented on app/lib/sdk/orbisDB/context.tsx
> +    };
Done!

2024-12-04 05:38 UTC, liberalterian commented on app/components/Videos/Upload/index.tsx
> +        // });
Done!

2024-12-04 06:03 UTC, liberalterian commented on app/api/livepeer/translation/route.ts
> +    });
Done!

2024-12-04 06:07 UTC, liberalterian commented on app/lib/sdk/orbisDB/context.tsx
> +  ],
Done!

2024-12-04 06:47 UTC, liberalterian commented on app/lib/sdk/orbisDB/context.tsx
> +    };
Done!

2024-12-04 06:50 UTC, liberalterian commented on app/lib/sdk/orbisDB/context.tsx
> +      };
Done!

2024-12-04 07:24 UTC, liberalterian commented on app/lib/sdk/orbisDB/context.tsx
> +    gateway: process.env.CERAMIC_NODE_URL || 'https://ceramic-orbisdb-mainnet-direct.hirenodes.io/',
This is producing a strange error. If it is required, I can look into it more tomorrow.

2024-12-04 07:26 UTC, liberalterian commented on app/lib/sdk/orbisDB/context.tsx
> +  };
This change is producing an error.

2024-12-04 19:24 UTC, liberalterian commented on app/lib/sdk/orbisDB/context.tsx
> +    gateway: process.env.CERAMIC_NODE_URL || 'https://ceramic-orbisdb-mainnet-direct.hirenodes.io/',
If I remove the hardcoded fallbacks, it thows the CERAMIC_NODE_URL required error. This is probably happening because the environment variables are not made public and aren't available on the client side.

Should I add "NEXT_PUBLIC_" to each variable? Or perhaps should I make these methods server actions instead of using a context API? 

I don't think there is any issue using these environment variables on the client side.

2024-12-04 22:40 UTC, liberalterian commented on app/lib/sdk/orbisDB/context.tsx
> +    gateway: process.env.CERAMIC_NODE_URL || 'https://ceramic-orbisdb-mainnet-direct.hirenodes.io/',
I was informed by the one of the OrbisDB devs that these variables are not sensitive and there is no problem making them public right now.

2024-12-04 22:44 UTC, liberalterian commented on app/api/livepeer/translation/route.ts
> +    // }
Done!

2024-12-04 22:47 UTC, liberalterian commented on app/lib/sdk/orbisDB/context.tsx
> +  };
Let's hold off on this for now. I have other things to take care right now and this is relatively low priority.

2024-12-04 22:49 UTC, liberalterian commented on .env.sample
> +ACCESS_WEBHOOK_ID="Webhook ID"
Let's hold off on this for now. None of the other env vars have descriptive comments. If we decide we need them we can get to it at that point in time.

2024-12-04 23:32 UTC, liberalterian commented on app/components/Player/Player.tsx
> +  };
Done!

2024-12-04 23:34 UTC, liberalterian commented on app/components/Button/connectButtonWrapper.tsx
> +  const activeWallet = useActiveWallet();
This is erroneous, there is no orbisError in OrbisProvider or OrbisContextProps.

2024-12-04 23:39 UTC, liberalterian commented on app/components/Button/connectButtonWrapper.tsx
>          },
Done!

2024-12-04 23:41 UTC, liberalterian commented on app/components/Button/connectButtonWrapper.tsx
> +          return loginPayload;
Done!

2024-12-04 23:43 UTC, liberalterian commented on app/components/Videos/Upload/index.tsx
> +            [subtitlesUri, setSubtitlesUri] = useState<string>();
Done!

2024-12-04 23:46 UTC, liberalterian commented on app/lib/sdk/orbisDB/models/AssetMetadata.ts
> +};
This is overkill. The JSON Schema in the original model definition comes directly from the OrbisDB Studio dashboard. Therefore, we should leave it as is.

2024-12-04 23:47 UTC, liberalterian commented on app/lib/sdk/orbisDB/models/AssetMetadata.ts
> +  }
Done!

2024-12-04 23:50 UTC, liberalterian commented on app/components/Button/actions/thirdwebAuth.ts
> +export const generatePayload = thirdwebAuth.generatePayload;
Done!

2024-12-05 00:08 UTC, liberalterian commented on app/components/Button/connectButtonWrapper.tsx
> +      }}
Done!

2024-12-05 00:11 UTC, liberalterian commented on app/components/Button/connectButtonWrapper.tsx
> +          }
Done!

2024-12-05 00:13 UTC, liberalterian commented on app/components/Player/Player.tsx
> +  }, [assetId]);
Done!

2024-12-05 00:13 UTC, liberalterian commented on app/components/Videos/VideoDetails.tsx
> +  const { getAssetMetadata } = useOrbisContext();
Done!

2024-12-05 00:14 UTC, liberalterian commented on app/api/livepeer/audio-to-text/route.ts
> +    // console.log('blob', blob);
Done!

2024-12-05 00:14 UTC, liberalterian commented on app/api/livepeer/audio-to-text/route.ts
> +    // }
Done!

2024-12-05 00:18 UTC, liberalterian commented on app/components/Videos/VideoDetails.tsx
> +    }
Done!

2024-12-05 10:46 UTC, amochuko reviewed
Well done. Here are my checks.

2024-12-05 19:21 UTC, merged

2024-12-05 22:45 UTC, liberalterian commented on app/api/livepeer/translation/route.ts
> +    const sanitizedText = text.trim();
We should look at adding this soon and include as part of the next milestone.

2024-12-05 22:51 UTC, liberalterian commented on app/api/livepeer/actions.ts
>    return asset;
I just added this. It will be included in my next PR.

2024-12-05 22:51 UTC, liberalterian commented on app/api/livepeer/actions.ts
>    return asset;
I just added this. It will be included in my next PR.

2024-12-05 22:52 UTC, liberalterian commented on app/api/livepeer/translation/route.ts
> +    console.error('Translation error:', error);
I just added this. It will also be included in my next PR.

2024-12-05 22:53 UTC, liberalterian commented on app/api/livepeer/actions.ts
>    return asset;
Do you mean remove try/catch from server actions in @app/api/livepeer/actions.ts and add similar error handling whenever we run them?

2024-12-05 22:56 UTC, liberalterian commented on app/api/livepeer/token-gate/route.ts
> +  const activeAccount = useActiveAccount();
I just set up custom JWT context in @app/api/auth/thirdweb/authentication.ts and added a getJwtContext function which we can use in the token-gate/route.ts or anywhere else on the backend to fetch the user's address. I also updated the @app/lib/utils/access-key.ts file to reflect these changes. I think this should work well, but I am not yet 100% on that.